In [2]:
import pandas as pd
import numpy as np

In [6]:
pit_counts = pd.read_csv("pit_counts.csv")
acs_data = pd.read_csv("../Data/raw/ACS_data.csv",
    dtype={
        'GEOID' : str,
        'Year' : int,
        'State' : str,
        'County' : str,
    }
)
hic_counts = pd.read_csv("hic_counts.csv")

pit_counts

,CoC Name,CoC Number,year,Count Types,Overall Homeless,Unsheltered Homeless,Sheltered Total Homeless,Overall Homeless Individuals,Overall Homeless People in Families
0,Anchorage CoC,AK-500,2024,Sheltered and Unsheltered Count,1709.0,346.0,1363.0,1321.0,388.0
1,Alaska Balance of State CoC,AK-501,2024,Sheltered and Unsheltered Count,977.0,133.0,844.0,698.0,279.0
2,"Birmingham/Jefferson, St. Clair, Shelby Counti...",AL-500,2024,Sheltered and Unsheltered Count,911.0,395.0,516.0,785.0,126.0
3,Mobile City & County/Baldwin County CoC,AL-501,2024,Sheltered and Unsheltered Count,675.0,351.0,324.0,441.0,234.0
4,Florence/Northwest Alabama CoC,AL-502,2024,Sheltered and Unsheltered Count,210.0,54.0,156.0,136.0,74.0
...,...,...,...,...,...,...,...,...,...
6166,West Virginia Balance of State CoC,WV-508,2009,Sheltered and Unsheltered Count,1003.0,333.0,670.0,616.0,387.0
6167,Wyoming Statewide CoC,WY-500,2009,Sheltered and Unsheltered Count,515.0,64.0,451.0,340.0,175.0
6168,Total,NaN,2009,NaN,630227.0,226919.0,403308.0,392131.0,238096.0
6169,NaN,NaN,2009,NaN,NaN,NaN,NaN,NaN,NaN
6170,NaN,a MO-604 covers territory in both Missouri and...,2009,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
acs_data

,GEOID,Year,State,County,TotalPopulation,MedianRent,MedianIncome,PovertyRate,PovertyNumerator,PovertyDenominator,...,VacancyDenominator,RenterOccupiedRate,RenterOccupiedNumerator,RenterOccupiedDenominator,RentBurdenedRate,RentBurdenedNumerator,RentBurdenedDenominator,UnemploymentRate,UnemploymentNumerator,UnemploymentDenominator
0,13091,2009,13,091,19695.0,441.345794,31334.0,0.223193,3805.0,17048.0,...,2365.0,0.302191,2096.0,6936.0,0.258588,542.0,2096.0,0.062580,442.0,7063.0
1,13093,2009,13,093,11641.0,447.167442,30172.0,0.274752,2553.0,9292.0,...,1378.0,0.339314,1286.0,3790.0,0.482893,621.0,1286.0,0.069630,271.0,3892.0
2,13095,2009,13,095,95330.0,576.910954,34597.0,0.252411,23294.0,92286.0,...,19881.0,0.505754,18589.0,36755.0,0.451073,8385.0,18589.0,0.122589,5339.0,43552.0
3,13097,2009,13,097,122657.0,851.066947,55512.0,0.109097,13260.0,121543.0,...,13968.0,0.293261,12441.0,42423.0,0.449883,5597.0,12441.0,0.096686,6199.0,64115.0
4,13099,2009,13,099,11812.0,345.409396,28063.0,0.269678,3111.0,11536.0,...,1562.0,0.311302,1380.0,4433.0,0.457246,631.0,1380.0,0.080719,355.0,4398.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48306,72145,2023,72,145,54058.0,575.841703,23877.0,0.422811,22724.0,53745.0,...,5553.0,0.246509,5049.0,20482.0,0.264607,1336.0,5049.0,0.134242,2660.0,19815.0
48307,72147,2023,72,147,8147.0,438.056250,17531.0,0.595311,4850.0,8147.0,...,1082.0,0.310552,827.0,2663.0,0.177751,147.0,827.0,0.085572,223.0,2606.0
48308,72149,2023,72,149,21778.0,465.833333,24882.0,0.418320,9065.0,21670.0,...,1655.0,0.213919,1623.0,7587.0,0.203943,331.0,1623.0,0.135114,1057.0,7823.0
48309,72151,2023,72,151,29868.0,429.811258,21279.0,0.497166,14826.0,29821.0,...,3490.0,0.292347,3438.0,11760.0,0.288540,992.0,3438.0,0.096726,913.0,9439.0
48310,72153,2023,72,153,33509.0,459.781022,21918.0,0.445574,14855.0,33339.0,...,3576.0,0.258735,3251.0,12565.0,0.190711,620.0,3251.0,0.130615,1547.0,11844.0

In [8]:
hic_counts

     COC_Number  Total_Year_Round_Beds  year
0        AK-500                  921.0  2024
1        AK-501                 1118.0  2024
2        AL-500                  563.0  2024
3        AL-501                  445.0  2024
4        AL-502                  211.0  2024
...         ...                    ...   ...
7447     WV-501                  381.0  2007
7448     WV-503                  416.0  2007
7449     WV-508                  969.0  2007
7450     WY-500                  729.0  2007
7451      Total               422656.0  2007

[7452 rows x 3 columns]

In [9]:
matches = pd.read_csv(
    'county_coc_match.csv',
    dtype={'county_fips': str}
)

matches

,county_fips,coc_number,coc_name,coc_name_PIT,in_2017_shapefile,in_2017_PIT,n_cocs_in_county,n_counties_in_coc,mult_county_mult_coc,rel_type,pct_cnty_pop_coc,pct_cnty_pov_coc
0,01001,AL-504,Montgomery City & County CoC,Montgomery City & County CoC,Yes,Yes,1.0,5.0,0.0,2.0,100.0,100.0
1,01003,AL-501,Mobile City & County/Baldwin County CoC,Mobile City & County/Baldwin County CoC,Yes,Yes,1.0,2.0,0.0,2.0,100.0,100.0
2,01005,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
3,01007,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
4,01009,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3297,60030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,60040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3299,60050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3300,NaN,AL-505,NaN,Gadsden/Northeast Alabama CoC,No,Yes,2.0,1.0,0.0,3.0,NaN,NaN
3301,NaN,AR-508,NaN,Old Fort Homeless Coalition,No,Yes,2.0,1.0,0.0,3.0,NaN,NaN

## Split DF into Relationship Types

There are four relationship types:
* 1: The boundaries of a single CoC and a single county are coterminous.
* 2: A CoC's boundary fully encompass multiple counties.
* 3: A single county fully contains multiple CoCs.
* 4: A CoC is partially located in multiple counties and the counties in which it is located also contain parts of multiple CoCs.

## Create Network of Geographies

In [16]:
matches

,county_fips,coc_number,coc_name,coc_name_PIT,in_2017_shapefile,in_2017_PIT,n_cocs_in_county,n_counties_in_coc,mult_county_mult_coc,rel_type,pct_cnty_pop_coc,pct_cnty_pov_coc
0,01001,AL-504,Montgomery City & County CoC,Montgomery City & County CoC,Yes,Yes,1.0,5.0,0.0,2.0,100.0,100.0
1,01003,AL-501,Mobile City & County/Baldwin County CoC,Mobile City & County/Baldwin County CoC,Yes,Yes,1.0,2.0,0.0,2.0,100.0,100.0
2,01005,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
3,01007,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
4,01009,AL-507,Alabama Balance of State CoC,Alabama Balance of State CoC,Yes,Yes,1.0,45.0,0.0,2.0,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3297,60030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3298,60040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3299,60050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3300,NaN,AL-505,NaN,Gadsden/Northeast Alabama CoC,No,Yes,2.0,1.0,0.0,3.0,NaN,NaN
3301,NaN,AR-508,NaN,Old Fort Homeless Coalition,No,Yes,2.0,1.0,0.0,3.0,NaN,NaN

# Create Groups from The Edge List

In [22]:
import networkx as nx

# Create a graph from the DataFrame edgelist
G = nx.from_pandas_edgelist(matches, source='coc_number', target='county_fips')

connected_graphs = list(nx.connected_components(G))

len(connected_graphs)

347

We have 347 Groups containing all of our CoC/County elements.

# Create a LookUp Map

We will create a dictionary so we can lookup each FIPS number or Coc number and see which group it is in.

In [24]:
# create a dictionary
element_to_group_map = {}

# Use enumerate() to get both the index (0, 1, 2...) and the list of FIPS
for group_index, elements in enumerate(connected_graphs):
    for element in elements:
        # We add 1 to the index to get group numbers 1-347
        # instead of 0-346.
        element_to_group_map[element] = group_index + 1

3635

# Apply Map to Data

In [28]:
acs_data['Group_Number'] = acs_data['GEOID'].map(element_to_group_map)
hic_counts['Group_Number'] = hic_counts['COC_Number'].map(element_to_group_map)
pit_counts['Group_Number'] = pit_counts['CoC Number'].map(element_to_group_map)
print(acs_data['Group_Number'].isna().sum())
print(len(acs_data))
print(hic_counts['Group_Number'].isna().sum())
print(len(hic_counts))
print(pit_counts['Group_Number'].isna().sum())
print(len(pit_counts))

43
48311
427
7452
89
6171

# Aggregate the Data Per Group

In [52]:
acs_data = acs_data.rename(columns={'Year':'year'})
acs_data.columns

Index(['GEOID', 'year', 'State', 'County', 'TotalPopulation', 'MedianRent',
       'MedianIncome', 'PovertyRate', 'PovertyNumerator', 'PovertyDenominator',
       'VacancyRate', 'VacancyNumerator', 'VacancyDenominator',
       'RenterOccupiedRate', 'RenterOccupiedNumerator',
       'RenterOccupiedDenominator', 'RentBurdenedRate',
       'RentBurdenedNumerator', 'RentBurdenedDenominator', 'UnemploymentRate',
       'UnemploymentNumerator', 'UnemploymentDenominator', 'Group_Number'],
      dtype='object')

In [54]:
agg_acs_data = acs_data.groupby(['Group_Number','year']).agg(
    # New_Column_Name = ('Original_Column_Name', 'Function')
    Total_Population   = ('TotalPopulation', 'sum'),
    Central_Tendency_Rent = ('MedianRent', 'mean'),
    Central_Tendency_Income = ('MedianIncome', 'mean'),
    Poverty_Numerator = ('PovertyNumerator', 'sum'),
    Poverty_Denominator = ('PovertyDenominator', 'sum'),
    Vacancy_Numerator = ('VacancyNumerator', 'sum'),
    Vacancy_Denominator = ('VacancyDenominator', 'sum'),
    Renter_Occupied_Numerator = ('RenterOccupiedNumerator', 'sum'),
    Renter_Occupied_Denominator = ('RenterOccupiedDenominator', 'sum'),
    Rent_Burdened_Numerator = ('RentBurdenedNumerator', 'sum'),
    Rent_Burdened_Denominator = ('RentBurdenedDenominator', 'sum'),
    Unemployment_Numerator = ('UnemploymentNumerator', 'sum'),
    Unemployment_Denominator = ('UnemploymentDenominator', 'sum')
)

print(agg_acs_data.isna().sum())
print(len(agg_acs_data))

Total_Population                 0
Central_Tendency_Rent          780
Central_Tendency_Income          0
Poverty_Numerator                0
Poverty_Denominator              0
Vacancy_Numerator                0
Vacancy_Denominator              0
Renter_Occupied_Numerator        0
Renter_Occupied_Denominator      0
Rent_Burdened_Numerator          0
Rent_Burdened_Denominator        0
Unemployment_Numerator           0
Unemployment_Denominator         0
dtype: int64
5160

In [55]:
hic_counts.columns

Index(['COC_Number', 'Total_Year_Round_Beds', 'year', 'Group_Number'], dtype='object')

In [56]:
year_mask = (hic_counts['year'] >= 2009) & (hic_counts['year'] <= 2023)
agg_hic_count = hic_counts[year_mask].groupby(['Group_Number','year']).agg(
    # New_Column_Name = ('Original_Column_Name', 'Function')
    Beds = ('Total_Year_Round_Beds', 'sum'))

print(len(agg_hic_count))
print(agg_hic_count.isna().sum())

5099
Beds    0
dtype: int64

In [57]:
pit_counts.columns

Index(['CoC Name', 'CoC Number', 'year', 'Count Types', 'Overall Homeless',
       'Unsheltered Homeless', 'Sheltered Total Homeless',
       'Overall Homeless Individuals', 'Overall Homeless People in Families',
       'Group_Number'],
      dtype='object')

In [58]:
year_mask = (pit_counts['year'] >= 2009) & (pit_counts['year'] <= 2023)
agg_pit_count = pit_counts[year_mask].groupby(['Group_Number','year']).agg(
    # New_Column_Name = ('Original_Column_Name', 'Function')
    Overall_Homeless = ('Overall Homeless', 'sum'),
    Unsheltered_Homeless = ('Unsheltered Homeless', 'sum'),
    Sheltered_Total_Homeless = ('Sheltered Total Homeless', 'sum'),
    Overall_Homeless_Individuals = ('Overall Homeless Individuals', 'sum'),
    Overall_Homeless_People_in_Families = ('Overall Homeless People in Families', 'sum')
)
print(len(agg_pit_count))
print(agg_pit_count.isna().sum())

4966
Overall_Homeless                       0
Unsheltered_Homeless                   0
Sheltered_Total_Homeless               0
Overall_Homeless_Individuals           0
Overall_Homeless_People_in_Families    0
dtype: int64

In [66]:
merged_data = pd.merge(left=agg_pit_count, right=agg_hic_count, on=['Group_Number','year'])
merged_data = pd.merge(left=merged_data, right=agg_acs_data, on=['Group_Number','year'])
merged_data = merged_data.reset_index()

In [67]:

merged_data

,Group_Number,year,Overall_Homeless,Unsheltered_Homeless,Sheltered_Total_Homeless,Overall_Homeless_Individuals,Overall_Homeless_People_in_Families,Beds,Total_Population,Central_Tendency_Rent,...,Poverty_Numerator,Poverty_Denominator,Vacancy_Numerator,Vacancy_Denominator,Renter_Occupied_Numerator,Renter_Occupied_Denominator,Rent_Burdened_Numerator,Rent_Burdened_Denominator,Unemployment_Numerator,Unemployment_Denominator
0,1.0,2009,377.0,114.0,263.0,305.0,72.0,345.0,374216.0,542.527835,...,59137.0,357123.0,4432.0,49630.0,45198.0,142004.0,20743.0,45198.0,13563.0,177931.0
1,1.0,2010,444.0,150.0,294.0,376.0,68.0,384.0,381477.0,568.151431,...,61591.0,364452.0,4504.0,49739.0,45235.0,144189.0,21068.0,45235.0,14524.0,182341.0
2,1.0,2011,433.0,146.0,287.0,333.0,100.0,375.0,383939.0,581.080426,...,63934.0,367802.0,4609.0,49927.0,45318.0,144149.0,21845.0,45318.0,16226.0,183093.0
3,1.0,2012,487.0,144.0,343.0,383.0,104.0,413.0,385379.0,605.302942,...,65763.0,370121.0,4355.0,50721.0,46366.0,144818.0,23005.0,46366.0,16514.0,183410.0
4,1.0,2013,515.0,116.0,399.0,446.0,69.0,458.0,385614.0,646.035799,...,68548.0,370986.0,3768.0,51691.0,47923.0,145192.0,23566.0,47923.0,16950.0,181638.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,347.0,2019,568186.0,211502.0,356684.0,396421.0,171765.0,353.0,235300.0,666.524681,...,37227.0,223075.0,1435.0,26979.0,25544.0,92601.0,10202.0,25544.0,5863.0,103016.0
4915,347.0,2020,580746.0,226278.0,354468.0,409134.0,171612.0,115.0,235382.0,652.069862,...,33776.0,223152.0,1291.0,26942.0,25651.0,92959.0,9736.0,25651.0,5208.0,105171.0
4916,347.0,2021,381491.0,55124.0,326367.0,237289.0,137564.0,323.0,233169.0,707.810225,...,33224.0,221239.0,1122.0,25101.0,23979.0,88872.0,9045.0,23979.0,5637.0,103139.0
4917,347.0,2022,583026.0,234146.0,348880.0,421952.0,161074.0,291.0,232302.0,786.178031,...,31229.0,221313.0,979.0,25043.0,24064.0,89943.0,8879.0,24064.0,5220.0,103655.0
4918,347.0,2023,653783.0,256973.0,396810.0,467596.0,186187.0,330.0,231933.0,815.151089,...,32399.0,221315.0,920.0,24860.0,23940.0,91613.0,8825.0,23940.0,4823.0,103919.0

In [70]:
Final_Data_Set = merged_data[['Group_Number','year','Overall_Homeless', 'Unsheltered_Homeless', 'Sheltered_Total_Homeless', 'Overall_Homeless_Individuals', 'Overall_Homeless_People_in_Families', 'Beds', 'Total_Population', 'Central_Tendency_Rent', 'Central_Tendency_Income' ]].copy()
Final_Data_Set['Poverty_Rate'] = merged_data['Poverty_Numerator'] / merged_data['Poverty_Denominator']
Final_Data_Set['Vacancy_Rate'] = merged_data['Vacancy_Numerator'] / merged_data['Vacancy_Denominator']
Final_Data_Set['Renter_Occupied_Rate'] = merged_data['Renter_Occupied_Numerator'] / merged_data['Renter_Occupied_Denominator']
Final_Data_Set['Rent_Burdened_Rate'] = merged_data['Rent_Burdened_Numerator'] / merged_data['Rent_Burdened_Denominator']
Final_Data_Set['Unemployment_Rate'] = merged_data['Unemployment_Numerator'] / merged_data['Unemployment_Denominator']
Final_Data_Set

,Group_Number,year,Overall_Homeless,Unsheltered_Homeless,Sheltered_Total_Homeless,Overall_Homeless_Individuals,Overall_Homeless_People_in_Families,Beds,Total_Population,Central_Tendency_Rent,Central_Tendency_Income,Poverty_Rate,Vacancy_Rate,Renter_Occupied_Rate,Rent_Burdened_Rate,Unemployment_Rate
0,1.0,2009,377.0,114.0,263.0,305.0,72.0,345.0,374216.0,542.527835,40785.6,0.165593,0.089301,0.318287,0.458936,0.076226
1,1.0,2010,444.0,150.0,294.0,376.0,68.0,384.0,381477.0,568.151431,42284.8,0.168996,0.090553,0.313720,0.465746,0.079653
2,1.0,2011,433.0,146.0,287.0,333.0,100.0,375.0,383939.0,581.080426,42635.4,0.173827,0.092315,0.314383,0.482038,0.088622
3,1.0,2012,487.0,144.0,343.0,383.0,104.0,413.0,385379.0,605.302942,43242.2,0.177680,0.085862,0.320167,0.496161,0.090039
4,1.0,2013,515.0,116.0,399.0,446.0,69.0,458.0,385614.0,646.035799,42300.2,0.184772,0.072895,0.330066,0.491747,0.093317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,347.0,2019,568186.0,211502.0,356684.0,396421.0,171765.0,353.0,235300.0,666.524681,48388.2,0.166881,0.053190,0.275850,0.399389,0.056913
4915,347.0,2020,580746.0,226278.0,354468.0,409134.0,171612.0,115.0,235382.0,652.069862,51598.0,0.151359,0.047918,0.275939,0.379556,0.049519
4916,347.0,2021,381491.0,55124.0,326367.0,237289.0,137564.0,323.0,233169.0,707.810225,54169.8,0.150172,0.044699,0.269815,0.377205,0.054654
4917,347.0,2022,583026.0,234146.0,348880.0,421952.0,161074.0,291.0,232302.0,786.178031,59067.4,0.141108,0.039093,0.267547,0.368974,0.050359
4918,347.0,2023,653783.0,256973.0,396810.0,467596.0,186187.0,330.0,231933.0,815.151089,60849.4,0.146393,0.037007,0.261317,0.368630,0.046411

In [71]:
Final_Data_Set.to_csv('../Data/Final_Data_Set.csv',index=False)